### ISSUE TITLE
运行demo的时候运行自定义shell脚本出问题

### ISSUE THREAD

**Issue by yangchao0033** [ibireme/YYKit#8]
`PhaseScriptExecution Run\ Script /Users/chaoyang/Library/Developer/Xcode/DerivedData/YYKit-Static-dgprtydmnneatjaxszjjpuyeiyso/Build/Intermediates/YYKit-Static.build/Debug-iphoneos/YYKit.build/Script-D9B2622F1BEF581D0038C00A.sh
    cd /Users/chaoyang/Desktop/IOS/库文件/YYKit-master/Framework
    /bin/sh -c /Users/chaoyang/Library/Developer/Xcode/DerivedData/YYKit-Static-dgprtydmnneatjaxszjjpuyeiyso/Build/Intermediates/YYKit-Static.build/Debug-iphoneos/YYKit.build/Script-D9B2622F1BEF581D0038C00A.sh

UFW (M iphoneos): ERROR: Build failed
Traceback (most recent call last):
  File "/Users/chaoyang/Library/Developer/Xcode/DerivedData/YYKit-Static-dgprtydmnneatjaxszjjpuyeiyso/Build/Intermediates/YYKit-Static.build/Debug-iphoneos/YYKit.build/Script-D9B2622F1BEF581D0038C00A.sh", line 812, in <module>
    run_build()
  File "/Users/chaoyang/Library/Developer/Xcode/DerivedData/YYKit-Static-dgprtydmnneatjaxszjjpuyeiyso/Build/Intermediates/YYKit-Static.build/Debug-iphoneos/YYKit.build/Script-D9B2622F1BEF581D0038C00A.sh", line 745, in run_build
    project = Project(os.path.join(os.environ['PROJECT_FILE_PATH'], "project.pbxproj"))
  File "/Users/chaoyang/Library/Developer/Xcode/DerivedData/YYKit-Static-dgprtydmnneatjaxszjjpuyeiyso/Build/Intermediates/YYKit-Static.build/Debug-iphoneos/YYKit.build/Script-D9B2622F1BEF581D0038C00A.sh", line 201, in __init__
    self.header_paths = [os.path.join(*x['pathComponents']) for x in self.public_headers]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 28: ordinal not in range(128)
Command /bin/sh failed with exit code 1`
不知道啥原因。。。

**Comment by ibireme** [comment]
先把 `/Users/chaoyang/Library/Developer/Xcode/DerivedData/` 下面关于 YY 的东西都删掉，然后 Clean 一下工程，直接运行 YYKitDemo.xcodeproj。

另外确保用 Xcode 7 以上版本运行～

**Comment by yangchao0033** [comment]
嗯嗯，可以了 里面的demo好强大，正在研究ing，多谢哈！
